config/routes.rb
Rails.application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  resources :pay_types

  resources :line_items do
    post :decrease, on: :member
  end
  
  resources :orders do
    post :ship, on: :member
  end

  resources :products do
    get :who_bought, on: :member
  end

  resources :products
  
  scope '(:locale)' do
    resources :orders
    resources :line_items
    resources :carts
    root 'store#index', as: 'store_index', via: :all
  end
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/pay_types_controller.rb
class PayTypesController < ApplicationController
  before_action :set_pay_type, only: [:show, :edit, :update, :destroy]

  # GET /pay_types
  # GET /pay_types.json
  def index
    @pay_types = PayType.all
  end

  # GET /pay_types/1
  # GET /pay_types/1.json
  def show
  end

  # GET /pay_types/new
  def new
    @pay_type = PayType.new
  end

  # GET /pay_types/1/edit
  def edit
  end

  # POST /pay_types
  # POST /pay_types.json
  def create
    @pay_type = PayType.new(pay_type_params)

    respond_to do |format|
      if @pay_type.save
        format.html { redirect_to @pay_type, notice: 'Pay type was successfully created.' }
        format.json { render :show, status: :created, location: @pay_type }
      else
        format.html { render :new }
        format.json { render json: @pay_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pay_types/1
  # PATCH/PUT /pay_types/1.json
  def update
    respond_to do |format|
      if @pay_type.update(pay_type_params)
        format.html { redirect_to @pay_type, notice: 'Pay type was successfully updated.' }
        format.json { render :show, status: :ok, location: @pay_type }
      else
        format.html { render :edit }
        format.json { render json: @pay_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pay_types/1
  # DELETE /pay_types/1.json
  def destroy
    @pay_type.destroy
    respond_to do |format|
      format.html { redirect_to pay_types_url, notice: 'Pay type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pay_type
      @pay_type = PayType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pay_type_params
      params.require(:pay_type).permit(:name)
    end
end

app/helpers/pay_types_helper.rb
module PayTypesHelper
end

app/views/pay_types/_form.html.erb
<%= form_with(model: pay_type, local: true) do |form| %>
  <% if pay_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pay_type.errors.count, "error") %> prohibited this pay_type from being saved:</h2>

      <ul>
      <% pay_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :pay_type_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pay_types/edit.html.erb
<h1>Editing Pay Type</h1>

<%= render 'form', pay_type: @pay_type %>

<%= link_to 'Show', @pay_type %> |
<%= link_to 'Back', pay_types_path %>

app/views/pay_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pay Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pay_types.each do |pay_type| %>
      <tr>
        <td><%= pay_type.name %></td>
        <td><%= link_to 'Show', pay_type %></td>
        <td><%= link_to 'Edit', edit_pay_type_path(pay_type) %></td>
        <td><%= link_to 'Destroy', pay_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pay Type', new_pay_type_path %>

app/views/pay_types/new.html.erb
<h1>New Pay Type</h1>

<%= render 'form', pay_type: @pay_type %>

<%= link_to 'Back', pay_types_path %>

app/views/pay_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pay_type.name %>
</p>

<%= link_to 'Edit', edit_pay_type_path(@pay_type) %> |
<%= link_to 'Back', pay_types_path %>